enyo.depends(
    //START DEPENDS
    "$lib/layout",
    "$lib/onyx",
    "css/TouchFeeds.css",
    "css/ListSelector.css",
    "encoder.js",
    "prototype.js",
    "database-enyo.js",
    "models/api.js",
    "models/preferences.js",
    "models/countable.js",
    "models/article-container.js",
    "models/subscription-container.js",
    "models/all-articles.js",
    "models/all-sources.js",
    "models/all-subscriptions.js",
    "models/article.js",
    "models/asyncWrappers.js",
    "models/credentials.js",
    "models/feeder.js",
    "models/folder.js",
    "models/folders.js",
    "models/folder-subscriptions.js",
    "models/load-more.js",
    "models/search.js",
    "models/shared.js",
    "models/follow.js",
    "models/sort-order.js",
    "models/starred.js",
    "models/subscription.js",
    //START VIEWS
    "libraries/Metrix/metrix.js",
    //"ScrollingList.js",
    //"RowServer.js",
    //"Dashboard.js",
    //"Launcher.js",
    "Main.js",
    "FeedsView.js",
    "ArticlesView.js",
    "SingleArticleView.js",
    "Login.js",
    "Preferences.js"
    //"ChildBrowser.js"
    /*
    //"Notifications.js"
    */
);
